Check - Is vocabulary exist before importing terms
GetDKAN/taxonomy_fixtures pull request #5
Opened 2017-07-18 01:12 UTC by rahulseth

Check - Is vocabulary exist before importing terms.

2017-07-31 14:46 UTC, dafeder requested changes

2017-07-31 14:46 UTC, dafeder commented on taxonomy_fixtures.module
> +	    drupal_set_message(t("Vocabulary - $machine_name not exist"), 'error');
Hi @rahulseth - two things:
1. We can't pass variables inside strings to the t() function, please use placeholders. See [t() documentation](https://api.drupal.org/api/drupal/includes%21bootstrap.inc/function/t/7.x)
2. I think the right wording would be "Vocabulary _vocab\_machine\_name_ does not exist."

Thanks!

2017-08-01 04:53 UTC, rahulseth commented
Thanks @acouch  @dafeder  for review the PR.
@dafeder  I made the suggested changes. Please review it. Thanks!

2017-08-01 18:45 UTC, dafeder approved these changes

2017-08-01 18:46 UTC, merged